### ISSUE TITLE
Song title and artist info

### ISSUE THREAD

**Issue by fmandal** [tma02/spotispy#1]
I miss the ability to show song title and artist info under album art.

**Comment by tma02** [comment]
This is definitely a feature I'm looking to implement as an option. Expect updates in a few days!

**Comment by tma02** [comment]
This is currently implemented in [v0.0.5](https://github.com/tma02/spotispy/releases/tag/v0.0.5).

**Comment by tma02** [comment]
I will close this now since it has been implemented. Let me know if you have comments on the implementation!
