### ISSUE TITLE
Invalid OAuth Token

### ISSUE THREAD

**Issue by karanjitsingh** [tma02/spotispy#16]
[kj@localhost spotispy]$ npm start

> spotispy@0.0.1 start /home/kj/bin/spotispy
> electron lib/main.js

enumerated 1 displays.
waiting for spotify...
4370
{ [Error: connect ECONNREFUSED 127.0.0.1:4370]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4370 }
{ [Error: socket hang up] code: 'ECONNRESET' }
connection failed; trying new port...
waiting for spotify...
4371
{ version: 9,
  client_version: '1.0.49.125.g72ee7853',
  running: true }
4371
waiting for authentication...
waiting for authentication...
ready to grab album art.
[TypeError: Cannot read property 'track_resource' of undefined]
{ error: { type: '4102', message: 'Invalid OAuth token' },
  version: 9,
  client_version: '1.0.49.125.g72ee7853',
  running: true }

**Comment by tma02** [comment]
Are you running the latest version available on GitHub?

**Comment by karanjitsingh** [comment]
Sorry, my bad. It works after I pulled the latest commit.
