### ISSUE TITLE
Albums Not showing 

### ISSUE THREAD

**Issue by Genjura** [tma02/spotispy#18]
Album covers stopped showing up
Had to sign up for a spotify dev account for web API and send token in header with 
config.headers['Authorization'] = 'Bearer *******'; 
in getJson function.

**Comment by tma02** [comment]
It looks like Spotify recently changed their web API to require OAuth tokens for the ```/v1/albums/``` endpoint. The plan now is to update Spotispy to support this API change.

**Comment by tma02** [comment]
I've recently found an unauthenticated endpoint on open.spotify.com that returns the album image URL. It's already been implemented into Baritone and I'll be implementing it here as soon as I can.

**Comment by noomSik** [comment]
So is this going to be solved soon?

**Comment by tma02** [comment]
I'll have time to work on the issue this Saturday.

**Comment by Frankity** [comment]
i did something cool but i'm, awaiting for your albun art update, kepp it up, good job.
![image](https://user-images.githubusercontent.com/1179431/27996847-090beda4-64b1-11e7-9306-5706a6b28051.png)

**Comment by tma02** [comment]
Fixed in f1940cc
