### ISSUE TITLE
Older Spotify Versions?

### ISSUE THREAD

**Issue by bollhoj** [tma02/spotispy#22]
I'm running an old version of Spotify (0.9.15.27.g87efe634), and I would love an app like this one. However, when I run Spotispy, it just says "Waiting for Spotify..." (see screenshot).

I'm guessing it is because I run an old version of Spotify, or does it support older versions as well? Tried to run the exe before and after starting spotify, on my laptop and desktop pc, no change. Do you just boot it up and wait? Are there no settings or anything like that? Sorry if I'm missing something obvious here, I know nothing of code or coding.

Grateful for any kind of response.

![spotispy](https://user-images.githubusercontent.com/30534846/28732006-7c6a13aa-73d6-11e7-87e2-28a6eca28c4d.png)

**Comment by bollhoj** [comment]
Tried to install the most recent version just now, and now it says "Connecting to Spotify..." instead of "Waiting for Spotify...", but I can see song details beneath it.

**Comment by tma02** [comment]
I'm not sure how far back the version support for Spotispy goes. As for the most recent version of Spotify, it should be fixed in f1940cc.
