### ISSUE TITLE
Stuck at "Waiting For Spotify" - Spotify changed the way you get the song metadata AGAIN

### ISSUE THREAD

**Issue by noomSik** [tma02/spotispy#23]
With the new Spotify update, Spotispy can't go any further than the "Waiting For Spotify..." screen.

Spotify changed again the port/security/way you retrieve the song metadata, and this affects other apps that used to use it like Musixmatch in Windows 10.

I suspect Musixmatch will roll an update someday, maybe it is helpful.

**Comment by tma02** [comment]
It looks like the only way to access the currently playing track now is through their OAuth web API. Let me know if you find anything else about Musixmatch.

**Comment by noomSik** [comment]
@tma02 as far as I know, they are aware the app stopped working due to the last Spotify update and are working on a new update that should come soon. 

However, they have direct contact with the Spotify team because they recently released a new feature of connecting both apps, so I wouldn't take for granted the existence of a way for third party apps to access currently playing track. Maybe they are restricting it to partners (Although if that was the case, I suppose they would tell it to Musixmatch instead of surprising them with this change). 

Is there a way to obtain the tokens for the OAuth API?

**Comment by tma02** [comment]
Thanks for the info. And yes, you can obtain API tokens but just authenticating with your Spotify account. It's just a barrier I don't think users would want to deal with on a local app.

**Comment by noomSik** [comment]
well I sure would. Logging in with an account is not a problem for me. I understand it may be hard to code from scratch though.

**Comment by NutritiousCookie** [comment]
I would certainly be fine with logging in, if you wanted to include that. I think as an optional feature it would be a nice backup in case Spotify messes with their metadata again.

**Comment by ObsidianDrone** [comment]
I would be fine with signing in, It's almost like they change it on purpose.... heh

**Comment by tma02** [comment]
It doesn't seem like a lot of people are actually opposed to signing in to access spotispy. If this remains the case, I will work on an update to comply with the API change.

**Comment by noomSik** [comment]
@tma02 Musixmatch was updated today. Their app remains the same, no Spotify Login required nor restarting of any kind. It just works. Unfortunately I can't get the code for you or the lines the update changed because it is a W10 App and I don't know how those work, but maybe you're able to reverse engineer it?

**Comment by tma02** [comment]
Interesting, thanks for the update. Maybe they're not using the Spotify Web API then. I'll have to investigate that.

**Comment by tma02** [comment]
I started reverse engineering Musixmatch today, it doesn't look like a lot has changed actually. I should be able to write a version that doesn't require user sign in.
