### ISSUE TITLE
MAC-OS 0.0.9?

### ISSUE THREAD

**Issue by natedog2424** [tma02/spotispy#25]
Can you PLEASE make a working version for OS X! 0.0.8 doesn't work and there isn't an OS X app on 0.0.9

**Comment by muuud** [comment]
If you would still like to install 0.0.9 before the official release is out, it is quick and easy to install the app from the source code, though it requires you to run a few commands from terminal as well as having node.js (https://nodejs.org/en/) installed. I used version 8.9.4 LTS.

Simply download the source archive (https://github.com/tma02/spotispy/archive/master.zip), unzip the file into a folder, and navigate to that folder in terminal. Should be as simple as
`cd ~/Downloads/spotispy-master/`
followed by the two commands required to install and start the application
```
npm install
npm start
```

**Comment by natedog2424** [comment]
Thank you for the reply! When will an installer version be available?

**Comment by muuud** [comment]
No idea my friend, I just found this software yesterday. @tma02 is the developer

**Comment by natedog2424** [comment]
Okay. Thanks for the quick reply and the detailed solution.
