### ISSUE TITLE
Will you also release the Windows version of v0.0.5?

### ISSUE THREAD

**Issue by hispan1c** [tma02/spotispy#4]

**Comment by tma02** [comment]
I'm going to be packaging a Windows and OS X version of the latest changes in just a bit.

**Comment by tma02** [comment]
A windows version has been released.

**Comment by hispan1c** [comment]
Fantastic, I love it!

Op 14 sep. 2016 06:21 schreef "Tianyi Ma" <notifications@github.com>:
