### ISSUE TITLE
After most recent Spotify update app no longer works.

### ISSUE THREAD

**Issue by NOSDOOM** [tma02/spotispy#7]
After Spotify updated to 1.0.37.150.gad02a02e the app no longer works, I think it's something with the webhelper, maybe just different ports but I'm not sure.

**Comment by tma02** [comment]
I'm investigating this issue right now. It seems like they're just forcing HTTPS on their local server.

**Comment by tma02** [comment]
This issue doesn't seem to be present on v0.0.5. Any more info on your current environment?

**Comment by tma02** [comment]
Correction, it seems like some of the ports did become dynamic. I have written a fix for v0.0.6.

**Comment by NOSDOOM** [comment]
Just gave the new update a try the windows zip works on windows 10. Thank you.

The other thing instead of separating the artist and album name with "<span id="artist"></span> - <span id="album"></span>" you might want to do it in js with "artist + ' ' + '-' + ' ' + album;" that way the - doesn't show up on the waiting for spotify and connecting to spotify screen before the artist and album name have loaded, but that's just nitpicking.

**Comment by tma02** [comment]
I can certainly hide the separator while Spotispy is still connecting, but since this issue is solved I will go ahead and close it.
