### ISSUE TITLE
How can one select which screen this has to go to?

### ISSUE THREAD

**Issue by philippeback** [tma02/spotispy#8]
At the moment the screen being picked up is the main screen and there seems to be no way to move spotispy to the other screen(s).

Would be nice to make it go to the other ones...

Win32 version

**Comment by philippeback** [comment]
Ahhh Ctrl-Shift-Arrows... Read the code Luke.

**Comment by tma02** [comment]
This should probably be mentioned in the readme.

**Comment by philippeback** [comment]
I see this is done 👍 Now, how is one building this thing would be welcome too.

**Comment by philippeback** [comment]
https://github.com/tma02/electron-quick-start may be useful to mention.

**Comment by tma02** [comment]
This has been done as well
